apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file ksqldb.yaml
    kompose.version: 1.19.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: ksqldb-server
  name: ksqldb-server
spec:
  ports:
  - name: "8088"
    port: 8088
    targetPort: 8088
  selector:
    io.kompose.service: ksqldb-server
status:
  loadBalancer: {}
